#!/usr/bin/env python3

import sys
from matchmakereft.libs.mm_offline import create_model, match_model_to_eft

model_name = sys.argv[1]

create_model(f"UnbrokenSM_BFM.fr {model_name}.fr")
match_model_to_eft(f"{model_name}_MM SMEFT_Green_Bpreserving_MM")
